### ISSUE TITLE
Delete duplicate file clip4:c

### ISSUE THREAD

**Issue by joruib** [fabiensanglard/gebbdoom#26]
The file clip4:c located at /src/code is an exact duplicate of clip4.c and to my knowledge (after a thorough search) unused in any of the .tex files.

I have been working on a fork of this repository for quite some time and the file checked out under Windows 7 with no problem when I forked around a year ago. Since then, I've deleted it and forgot about this but a couple of days ago I cloned again this repository to a new computer (so that I could build a fresh copy of the original) and the cloning failed while trying to check out the file under Windows 10.

Under Linux and Mac this checked out ok, but since the file seems unused, I suggest to delete it so that the repository can be cloned under Windows.

Here is the output I get:
```
$ git clone https://github.com/fabiensanglard/gebbdoom.git gebbdoom
Cloning into 'gebbdoom'...
remote: Enumerating objects: 5933, done.
remote: Total 5933 (delta 0), reused 0 (delta 0), pack-reused 5933
Receiving objects: 100% (5933/5933), 810.87 MiB | 615.00 KiB/s, done.
Resolving deltas: 100% (3912/3912), done.
error: invalid path 'src/code/clip4:c'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

**Comment by fabiensanglard** [comment]
Done. Thanks for reporting this issue.
