### ISSUE TITLE
can't find file `tkz-obj-angles.tex'

### ISSUE THREAD

**Issue by choas** [fabiensanglard/gebbdoom#28]
I've figured out that Ubuntu 20.04 (docker image) uses tkz-euclide version >= 3.02. This causes an error: _can't find file `tkz-obj-angles.tex'_. 

Since version 3.02 \usetkzobj{all} is not necessary (see [LaTeX can't find file 'tkz-obj-angles.tex'](https://tex.stackexchange.com/questions/529550/latex-cant-find-file-tkz-obj-angles-tex/529562#529562)).

**Comment by fabiensanglard** [comment]
I think the latest version of texlive solved this issue.
