### ISSUE TITLE
?? reference to graphic

### ISSUE THREAD

**Issue by rofl0r** [fabiensanglard/gebbdoom#33]
page 230: in figure ??

also on page 354 is a typo "required to coordinate**s** 8 chips"

thanks for releasing these great books.

btw would it be possible to have additional smaller versions (like 150 dpi)? 300 dpi might be great to produce a physical book, but i don't think i can afford to keep a 160 MB pdf in my collection.

some more feedback: i had hoped the section dealing with the OPL2 in the wolf3d book would be a little bit more detailed. the doom book could illustrate a specific sbi instrument as an example and from what parameters it is composed of.

**Comment by fabiensanglard** [comment]
page 230 ???, fixed in e06af5801311adede4639669d37356ae7a792a3c

**Comment by fabiensanglard** [comment]
p354 coordinateS typo fixed in cfeb7b8cb00fb671821754c76e0ea94fa5e302f2

**Comment by fabiensanglard** [comment]
I ran the books throught Adobe optimizer, the 300dpi version is only 35 MiB now.

**Comment by fabiensanglard** [comment]
I did my best on the OPL2 but audio is definitely my weakness. If you feel the skills and the energy, you are welcome to contribute a double page for it (in order not to mess up the layout) and send a PR :) !

Thank for taking the time to report these issues.
