### ISSUE TITLE
'build engine' => 'BUILD Engine'

### ISSUE THREAD

**Issue by cher-nov** [fabiensanglard/gebbdoom#35]
https://github.com/fabiensanglard/gebbdoom/blob/ca419bfc87e94a623bf1b1a769e59b31c30e4e5f/src/software_3drenderer.tex#L39

This must be a proper noun, not a common one, I guess.

**Comment by fabiensanglard** [comment]
Fixed in 11603cb62d916c7a8548796c96b253012c3e5e43.

Thanks for taking the time to report this issue.
