### ISSUE TITLE
Jaguar RISC engines couldn't execute code from main memory

### ISSUE THREAD

**Issue by fonic** [fabiensanglard/gebbdoom#37]
In the _Game Engine Black Book v1.1_, _chapter 6.1.2_, _page 305_, John Carmack is quoted stating this:

```
The little RISC engines were decent processors. I was surprised that they
didn’t use off the shelf designs, but they basically worked ok. They had some
design hazards (write after write) that didn’t get fixed, but the only thing truly
wrong with them was that they had scratchpad memory instead of caches, and
couldn’t execute code from main memory. I had to chunk the DOOM renderer
into nine sequentially loaded overlays to get it working (with hindsight, I would
have done it differently in about three...).
```

This is closely related to a previous paragraph on _page 301/302_:

![gebbdoom_page_301_302](https://user-images.githubusercontent.com/14027079/199970640-dcd1af22-6a8f-4971-a71b-58b3436423bd.png)

While not wrong per se, I think this could use some clarification. The Jaguar's RISC engines **could in fact execute code from main memory** (DRAM) and were designed/meant to do so, **BUT** another one of those design hazards prevented this in practice:

![jaguar_technical_reference_manual_rev8_page_137](https://user-images.githubusercontent.com/14027079/199964698-31abd783-403e-4fc8-980c-012e2b44b50f.png)

So code could indeed be executed from main memory, but jump instructions were unreliable. Since jumps are an essential part of almost every algorithm, this practically renders code execution from main memory useless.

---

I think this is worth pointing out since it further explains why the Jaguar was so hard to deal with for developers (which in turn highlights what a genius John Carmack was back then to be able to pull it off). This was not just another minor design hazard that could be easily worked around, but instead a major deal-breaker. Even though execution from the RISCs' local scratchpad memory was much faster and the preferred choice, being able to execute code from main memory would have made development A LOT easier (i.e. simply use main memory during development, then chunk the FINAL code for use in scratchpad memory as an optimization step late in the development cycle).

**Comment by fabiensanglard** [comment]
Fixed in ac69b84a3f4d9934280b724d179d949b6729113d

**Comment by fonic** [comment]
I'd suggest changing the text to:
```
Jumps could fail when executed from main memory (see Jaguar Tech Reference Manual Rev. 8, p137)
```
as the actual instructions are named `JUMP`/`JR` (not `jmp`) and as there are multiple of these tech references around (I found three different versions myself).

**Comment by fabiensanglard** [comment]
There is not enough space to change the sentence as you suggested.

**Comment by fonic** [comment]
Yeah, that's what I thought - I compiled the book and noticed that there doesn't seem to be lots of space left down there.
