### ISSUE TITLE
Jaguar port of DOOM lacks music due to ... ?

### ISSUE THREAD

**Issue by fonic** [fabiensanglard/gebbdoom#38]
In the _Game Engine Black Book v1.1_, _chapter 6.1.2_, _page 303_, the reason for the Jaguar port of DOOM lacking music is explained as follows:

![gebbdoom_page_303_lack_of_music](https://user-images.githubusercontent.com/14027079/199989382-769ff064-786b-4d50-984a-cd784172472f.png)

However, in [AVGN](https://www.youtube.com/AngryNintendoNerd)'s DOOM video that aired on 11/01, a rather different version of events is described (transcript of relevant section):

_Shortly after that episode, I got a message from [level] designer Sandy Petersen, explaining the situation. I'll just summarize by saying it was a money issue. From what I was told, the contract with the composer meant having to pay him the same amount for the Jaguar version as the PC version, and clearly the Jaguar would sell far less copies. He ended by saying: "I know that's a shitty reason to leave out the music, but there you have it."_

Video:
https://youtu.be/f5zyhC11hzQ?t=1120

Really interesting. Two entirely different reasons. Could it be that there were technical issues first (as described [here](https://forums.atariage.com/topic/287323-enabling-music-sound-fx-mixing-within-jaguar-doom-source/page/2/#comment-4239037)), but THEN the financial issue came up, leading to simply disabling music and not bother with fixing the technical issues as it was no longer necessary?

Here's what I could find on the topic (probably what you used for the book in the first place):
https://forums.atariage.com/topic/69035-doom-music/
https://forums.atariage.com/topic/266578-why-no-music-on-jag-doom/
https://hackaday.com/2019/08/04/doing-what-id-couldnt-returning-music-to-jaguar-doom/
https://forums.atariage.com/topic/287323-enabling-music-sound-fx-mixing-within-jaguar-doom-source/page/2/#comment-4239037

**Comment by fabiensanglard** [comment]
It could have been both. I have emailed John, maybe he can share his recollection of it.

**Comment by fonic** [comment]
> It could have been both. I have emailed John, maybe he can share his recollection of it here.

If John Carmack were to show up in this thread I'd finally consider my life as being complete ;)

**Comment by yvesgurcan** [comment]
Funny! I had the same reaction after watching the video by the AVGN. I was under the impression that the issue was indeed technical, not financial.

**Comment by fonic** [comment]
> Funny! I had the same reaction after watching the video by the AVGN. I was under the impression that the issue was indeed technical, not financial.

I lean towards thinking it was both. There certainly were technical issues as everyone who tried to reactivate music output ran into quite a few problems (but none of a magnitude that would have prevented John Carmack from fixing it himself within a reasonable time frame). It's also conceivable that J.C. would remember the issue being technical as development was his main focus - I doubt that he dealt with organizational tasks like licensing music, thus he would have been much less involved in issues that might have arisen in that department.

**Comment by fabiensanglard** [comment]
Here is John's answer:

`I do not remember a contract issue, but I wouldn’t stake much on that.  AFAIK, music has never been on a flat fee per platform basis; that would be very weird. There wasn’t a lot of performance or memory margin on the Jaguar, I wouldn’t have sacrificed any framerate for the music.`

**Comment by fonic** [comment]
Really nice of him to give his thoughts on the topic.

You could reach out to Sandy Petersen to confirm - his description seems to be to specific to be a random fluke.

**Comment by fabiensanglard** [comment]
Sandy already shared his recollection via the Youtube video linked in this entry initial post. My conclusion is that this was a technical issue and the contract issue (the music would be licensed on a per platform basis) makes little sense to me.  I will leave it the way it is in the book.
