### ISSUE TITLE
A.I fsunctions are called when entering a state. Not on every tic.

### ISSUE THREAD

**Issue by fabiensanglard** [fabiensanglard/gebbdoom#39]
Reported by Raigan Burns via email:

> On p.266 you mention that when the Imp is in the stand state, "A_Look is called each tic trying to locate the player" -- actually this isn't true, the action functions are only called on the first tick of each state/frame, which means A_Look will only be triggered every 10 tics (since the Imp's standing states/frames last 10 tics).
> 
> Initially I was really confused about this design, since it means all those monsters with 3-tic duration A_Chase movement states will have their positions crudely animated at only about 11hz, which you'd think would look too step-y, but I verified this on a couple Doom modding forums: action functions are only called on the initial frame of the state, and monsters really do only move around the world at ~11hz (demons have 2-tic durations for A_Chase so they're a bit smoother).
> 
> (Also, since the initial tic value of each mobj is randomized when they get placed on the map, this means that it's sort of a work-balancing system since this way every monster isn't calling A_Chase every frame, they get spread around.)

**Comment by fabiensanglard** [comment]
Indeed, this is a mistake.  The current phrasing is as follows.

>  Upon simulating each game tic, the engine looks at
> what to do in this state. In this case, the imp will cycle between the states S_TROO_STND and
> S_TROO_STND2. In these sub-states, A_Look is called each tic trying to locate the player.

I think I can rephrase and still remain within the right amount of realestate.

> Upon entering a state, the engine calls its associated function. In this case, the imp will cycle between the states S_TROO_STND and S_TROO_STND2. This means, A_Look is called at 11Hz.

**Comment by fabiensanglard** [comment]
Fixed in 8ed83a7bf97e4396c3f9021015cd16830871ce76

**Comment by fabiensanglard** [comment]
Fixed in 8ed83a7bf97e4396c3f9021015cd16830871ce76

**Comment by BenMcLean** [comment]
I can confirm that Action methods are called once per actor state, while Think methods are called every tic.

**Comment by fabiensanglard** [comment]
I am not familiar with the difference between Act method and Think methods. Do you have a link to the source so I can take a look?
