### ISSUE TITLE
pg 277 - Thinker Function Pointer Differs from Usage in Description

### ISSUE THREAD

**Issue by ode2spot** [fabiensanglard/gebbdoom#69]
First off, thank you for this book!

Suggestion on pg 277 - it would be more correct to define _think_t_ as `typedef void (* think_t ) ( void* ) ;` to match its usage on this page.

It is currently reads as follows:

```typedef void (* think_t ) () ;

typedef struct thinker_s {
  struct thinker_s * prev , * next ;
  think_t function ;
} thinker_t ;
```

but in the instance of _floor_, it points to a function with the signature:

```
void T_MoveFloor ( floormove_t * floor ) ;

[...]

floor->thinker.function = ( think_t ) T_MoveFloor ;
```

There has been some simplification made to actual source code - the _think_t_ type describes a union of function pointers, and the signature for the simplified _think_t_ does not match its usage here.

**Comment by fabiensanglard** [comment]
Thank you for these kind words. Please elaborate on the proposed change. I am not following :P !

**Comment by ode2spot** [comment]
I just realized what I thought was an error actually does work.  In the lines:

`typedef void (* think_t ) () ;
void T_MoveFloor ( floormove_t * floor ) ;

[...]

floor->thinker.function = (think_t) T_MoveFloor ;`

Casting  _T_MoveFloor_ to _think_t_ works even though they have different signatures, scary! :>
Thanks for your time and thanks again for a great book!
